classes:
- system.linux.system.repo.ubuntu
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.salt.minion.cert.k8s_server
- system.reclass.storage.salt
#- system.reclass.storage.system.kubernetes_control_cluster
- cluster.virtual-mcp11-k8s-calico-aws.kubernetes.control
- cluster.virtual-mcp11-k8s-calico-aws
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/tomkukral/kubernetes-aws-model.git"
    reclass_data_revision: allinone
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$WV0P1shnoDh2gI/Z$22/Bcd7ffMv0jDlFpT63cAU4PiXHz9pjXwngToKwqAsgoeK4HNR3PiKaushjxp3JsQ8hNoJmAC6TxzVqfV8WH/"
    salt_master_host: 127.0.0.1
    kubernetes_control_node01_hostname: ctl01
    kubernetes_control_node02_hostname: ctl02
    kubernetes_control_node03_hostname: ctl03
    keepalived_vip_priority: 103
  salt:
    master:
      worker_threads: 6
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
      environment:
        prd:
          formula:
            kubernetes:
              source: git
              address: https://github.com/tomkukral/salt-formula-kubernetes.git
              revision: workshop-aio
    minion:
      cert:
        k8s_server:
          alternative_names: DNS:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address},DNS:kubernetes.default,DNS:kubernetes.default.svc
  reclass:
    storage:
      data_source:
        engine: local
      class_mapping:
        common_node:
          expression: all
          node_param:
            single_address:
              value_template: <<node_deploy_ip>>
            linux_system_codename:
              value_template: <<node_os>>
            salt_master_host:
              value_template: <<node_master_ip>>
        kubernetes_control01:
          expression: <<node_hostname>>__equals__ctl01
          cluster_param:
            kubernetes_control_node01_address:
              value_template: <<node_deploy_ip>>
            infra_config_address:
              value_template: <<node_deploy_ip>>
            infra_config_deploy_address:
              value_template: <<node_deploy_ip>>
            cluster_domain:
              value_template: <<node_domain>>
        kubernetes_control02:
          expression: <<node_hostname>>__equals__ctl02
          cluster_param:
            kubernetes_control_node02_address:
              value_template: <<node_deploy_ip>>
        kubernetes_control03:
          expression: <<node_hostname>>__equals__ctl03
          cluster_param:
            kubernetes_control_node03_address:
              value_template: <<node_deploy_ip>>
        kubernetes_compute:
          expression: <<node_hostname>>__startswith__ip
          node_class:
            value_template:
              - cluster.<<node_cluster>>.kubernetes.compute
      node:
        kubernetes_control_node02:
          name: ${_param:kubernetes_control_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_control_node02_address}
            keepalived_vip_priority: 102
        kubernetes_control_node03:
          name: ${_param:kubernetes_control_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_control_node03_address}
            keepalived_vip_priority: 101
